version: "3.9"
services:
  front-end:
    container_name: front-end
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  cart-app:
    container_name: cart-app
    build:
      context: ./cart
      dockerfile: Dockerfile
  catalogue-app:
    container_name: catalogue-app
    build:
      context: ./catalogue
      dockerfile: Dockerfile
  users-app:
    container_name: users-app
    build:
      context: ./users
      dockerfile: Dockerfile
  orders-app:
    container_name: orders-app
    build:
      context: ./orders
      dockerfile: Dockerfile
 