version: "3.9"
services:
  front-end:
    container_name: front-end
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  cart-app:
    container_name: cart-app
    build:
      context: ./cart
      dockerfile: Dockerfile
  catalogue-app:
    container_name: catalogue-app
    build:
      context: ./catalogue
      dockerfile: Dockerfile
  catalogue-db:
    container_name: catalogue-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: ./database/cataloguedb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
  users-app:
    container_name: users-app
    build:
      context: ./users
      dockerfile: Dockerfile
  users-db:
    container_name: users-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: ./database/usersdb
      dockerfile: Dockerfile
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
  orders-app:
    container_name: orders-app
    build:
      context: ./orders
      dockerfile: Dockerfile
  orders-db:
    container_name: orders-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: ./database/ordersdb
      dockerfile: Dockerfile
    ports:
      - "3308:3308"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678